language: python
python:
  - 3.6
sudo: false
install:
  - wget https://github.com/jgm/pandoc/releases/download/1.19.1/pandoc-1.19.1-1-amd64.deb && sudo dpkg -i pandoc-1.19.1-1-amd64.deb
  - pip install -r docs/requirements.txt
script:
  - cd docs; make html linkcheck